# Extract metrics of interest from Fastp report.json and print to the terminal

# Evan Hackstadt
# Whittall Lab Dudleya Genomics
# November 2025


import sys
import argparse
import json

# to run the script from CLI
parser = argparse.ArgumentParser()
parser.add_argument("json", help="path to the .json report generated by Fastp", type=str)
args = parser.parse_args()

path = args.json

# read our json file & extract data
with open(path, "r") as read_file:
    fastp_data = json.load(read_file)

# we now have json data as nested dictionaries
# extract and whatever values we want
saved = {}
saved['duplication_rate'] = fastp_data['duplication']['rate']
saved['total_reads'] = fastp_data['summary']['before_filtering']['total_reads']
saved['passed_filter_reads_#'] = fastp_data['filtering_result']['passed_filter_reads']
saved['passed_filter_reads_%'] = saved['passed_filter_reads_#'] / saved['total_reads']

# BROKEN FOR NOW
# % reads not overlapped requires some math since it is not logged directly
# copied source code logic (https://github.com/OpenGene/fastp/blob/master/src/htmlreporter.cpp)
'''
insert_size_unknown = fastp_data['insert_size']['unknown']
hist = fastp_data['insert_size']['histogram']
allCount = sum(hist)
insert_size_max = 270

saved['reads_not_overlapped_%'] = hist[insert_size_max] * 100.0 / allCount
'''

# print the values we extracted
for key, val in saved.items():
    print(key, " = ", val)

