# Evan Hackstadt
# Whittall Lab Dudleya Genomics
# 20 April 2026
# Note: initial code generated by Claude Sonnet 4.6

"""
Aggregate QC metrics across samples from fastp JSON and samtools flagstat outputs.
Produces a summary CSV and a read-attrition + mapping-rate plot.
"""

import os
import json
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns


# --- Parse fastp JSON ---

def parse_fastp(json_path):
    with open(json_path) as f:
        d = json.load(f)
    summary = d["summary"]
    bf = summary["before_filtering"]
    af = summary["after_filtering"]
    filtering = d["filtering_result"]
    return {
        "raw_reads":          bf["total_reads"],
        "raw_bases":          bf["total_bases"],
        "post_fastp_reads":   af["total_reads"],
        "passed_filter":      filtering["passed_filter_reads"],
        "low_quality":        filtering["low_quality_reads"],
        "too_short":          filtering["too_short_reads"],
        "too_many_N":         filtering["too_many_N_reads"],
    }


# --- Parse samtools flagstat ---

def parse_flagstat(flagstat_path):
    with open(flagstat_path) as f:
        text = f.read()
    
    def extract(pattern):
        m = re.search(pattern, text, re.MULTILINE)  # re.MULTILINE so ^ matches line starts
        return int(m.group(1)) if m else None

    total  = extract(r"^(\d+) \+ \d+ in total")
    mapped = extract(r"^(\d+) \+ \d+ mapped")
    return {
        "flagstat_total": total,
        "mapped_reads":   mapped,
        "mapping_rate":   round(100 * mapped / total, 2) if (total and mapped) else None
    }


# --- Parse summed depthSample ---

def parse_depth_sample(depth_path):
    """
    Parses a (summed) ANGSD depthSample file.
    Each row = one sample; columns = site counts at depth 0, 1, 2, ..., maxDepth.
    Returns a list of dicts, one per sample (in BAM list order).
    """
    arr = np.loadtxt(depth_path)    # shape: (n_samples, maxDepth+1)
    
    if arr.ndim == 1:
        arr = arr[None, :]          # single-sample edge case

    records = []
    depths = np.arange(arr.shape[1])   # [0, 1, 2, ..., maxDepth]

    for row in arr:
        total_sites   = row.sum()
        covered_sites = row[1:].sum()                    # sites with depth >= 1
        mean_depth    = (depths[1:] * row[1:]).sum() / covered_sites if covered_sites > 0 else 0
        records.append({
            "angsd_total_sites":   int(total_sites),
            "angsd_covered_sites": int(covered_sites),
            "angsd_mean_depth":    round(mean_depth, 2),
        })
    return records

# --- Aggregate ---

depth_records = parse_depth_sample(snakemake.input.depthSample)

records = []
for (json_path, flagstat_path, depth_rec) in zip(snakemake.input.fastp_jsons,
                                                  snakemake.input.flagstats,
                                                  depth_records):
    sample = os.path.basename(json_path).replace("FastpFilterReport_", "").replace(".json", "")
    pop    = sample.split("_LP_")[0]
    row    = {"sample": sample, "population": pop}
    row.update(parse_fastp(json_path))
    row.update(parse_flagstat(flagstat_path))
    row.update(depth_rec)
    records.append(row)

df = pd.DataFrame(records).sort_values("sample")

# Derived columns
df["fastp_retention_pct"] = 100 * df["post_fastp_reads"] / df["raw_reads"]
df["reads_lost_fastp"]    = df["raw_reads"] - df["post_fastp_reads"]
df["reads_lost_mapping"]  = df["post_fastp_reads"] - df["mapped_reads"]

# Flag potentially problematic samples (thresholds are adjustable)
LOW_READS_THRESHOLD   = 1_000_000   # fewer than 1M mapped reads
LOW_MAPPING_THRESHOLD = 70.0        # below 70% mapping rate
LOW_DEPTH_THRESHOLD = 3.0   # mean depth below 3x is generally unreliable

df["flag_low_reads"]   = df["mapped_reads"] < LOW_READS_THRESHOLD
df["flag_low_mapping"] = df["mapping_rate"] < LOW_MAPPING_THRESHOLD
df["flag_low_depth"] = df["angsd_mean_depth"] < LOW_DEPTH_THRESHOLD
df["flagged"]        = df["flag_low_reads"] | df["flag_low_mapping"] | df["flag_low_depth"]

# Save CSV
df.to_csv(snakemake.output.csv, index=False)
print(f"QC table saved to {snakemake.output.csv}")
print(f"\nFlagged samples ({df['flagged'].sum()} total):")
print(df[df["flagged"]][["sample", "mapped_reads", "mapping_rate"]])


# --- Plots ---

fig, axes = plt.subplots(4, 1, figsize=(max(14, len(df) * 0.12), 18))
fig.suptitle(f"Aggregate QC — {len(df)} samples", fontsize=14, y=1.01)

samples   = df["sample"]
x         = np.arange(len(df))
bar_width = 0.8

# --- Panel 1: Read attrition stacked bar ---
ax1 = axes[0]
ax1.bar(x, df["mapped_reads"],       width=bar_width, label="Mapped",            color="#4C72B0")
ax1.bar(x, df["reads_lost_mapping"], width=bar_width, label="Lost at mapping",   color="#DD8452",
        bottom=df["mapped_reads"])
ax1.bar(x, df["reads_lost_fastp"],   width=bar_width, label="Lost at fastp",     color="#C44E52",
        bottom=df["mapped_reads"] + df["reads_lost_mapping"])

# Mark flagged samples
flagged_x = x[df["flagged"].values]
ax1.scatter(flagged_x,
            df.loc[df["flagged"], "raw_reads"] * 1.02,
            marker="v", color="black", s=20, zorder=5, label="Flagged")

ax1.set_title("Read Attrition per Sample")
ax1.set_ylabel("Read count")
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v/1e6:.1f}M"))
ax1.set_xticks([])
ax1.legend(fontsize=8, loc="upper right")
ax1.axhline(LOW_READS_THRESHOLD, color="black", linestyle="--", linewidth=0.8, alpha=0.5)

# --- Panel 2: Mapping rate per sample ---
ax2 = axes[1]
colors = ["#C44E52" if f else "#4C72B0" for f in df["flagged"]]
ax2.bar(x, df["mapping_rate"], width=bar_width, color=colors)
ax2.axhline(LOW_MAPPING_THRESHOLD, color="black", linestyle="--", linewidth=0.8,
            label=f"Threshold ({LOW_MAPPING_THRESHOLD}%)")
ax2.set_title("Mapping Rate per Sample")
ax2.set_ylabel("% reads mapped")
ax2.set_ylim(0, 105)
ax2.set_xticks([])
ax2.legend(fontsize=8)

# --- Panel 3: Mapped read count distribution by population ---
ax3 = axes[2]
pop_order = df.groupby("population")["mapped_reads"].median().sort_values().index
sns.boxplot(data=df, x="population", y="mapped_reads",
            order=pop_order, ax=ax3, color="#4C72B0",
            flierprops={"marker": "o", "markersize": 3})
ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v/1e6:.1f}M"))
ax3.axhline(LOW_READS_THRESHOLD, color="black", linestyle="--", linewidth=0.8, alpha=0.7)
ax3.set_title("Mapped Read Distribution by Population")
ax3.set_xlabel("Population")
ax3.set_ylabel("Mapped reads")
ax3.tick_params(axis="x", rotation=45)

# --- Panel 4: Mean depth per sample post-ANGSD ---
ax4 = axes[3]
colors = ["#C44E52" if f else "#4C72B0" for f in df["flag_low_depth"]]
ax4.bar(x, df["angsd_mean_depth"], width=bar_width, color=colors)
ax4.axhline(LOW_DEPTH_THRESHOLD, color="black", linestyle="--", linewidth=0.8,
            label=f"Threshold ({LOW_DEPTH_THRESHOLD}x)")
ax4.set_title("Mean Depth per Sample (post-ANGSD filters)")
ax4.set_ylabel("Mean depth (x)")
ax4.set_xticks(x)
ax4.set_xticklabels(df["sample"], rotation=90, fontsize=4)
ax4.legend(fontsize=8)

plt.tight_layout()
plt.savefig(snakemake.output.plot, dpi=300, bbox_inches="tight")
print(f"QC plot saved to {snakemake.output.plot}")