# Visualize IQ-TREE consensus tree from a .contree file
# Note: initially generated by Claude 4.6 Sonnett

# Evan Hackstadt
# Whittall Lab Dudleya Genomics
# 16 April 2026

import os
import toytree
import toyplot
import toyplot.png


def plot_tree(tree_path, out_path):
    """
    Renders a consensus tree with bootstrap support labels.

    Args:
        tree_path (str): Path to the .contree file
        out_path (str): Path to write the output PNG
    """
    tree = toytree.tree(tree_path)

    canvas, axes, mark = tree.draw(
        width=800,
        height=max(400, tree.ntips * 14),   # scale height to number of tips
        tip_labels=True,
        tip_labels_style={"font-size": "9px"},
        node_labels="support",              # show bootstrap values
        node_labels_style={"font-size": "7px"},
        node_sizes=8,
        node_colors="lightgrey",
        scalebar=True,
        layout="right",
    )

    toyplot.png.render(canvas, out_path)
    print(f"Tree saved to {out_path}")


# --- Snakemake Arg Handling ---
tree_path = snakemake.input[0]
out_path = snakemake.output[0]

plot_tree(tree_path, out_path)