# Analyze genetic distance matrix output from ngsDist
#
# Distance matrix format (ngsDist output):
#   Line 1: empty
#   Line 2: number of samples (integer)
#   Lines 3+: <sample_label>\t<d1>\t<d2>\t...\t<dN>
#
# Species inference logic:
#   CY_*        -> DUCY (D. cymosa)
#   ABMU/ABBE/ABAB_* -> DUAB (D. abramsii)
#   all others  -> DUSE (D. setchellii)
#
# Analyses:
#   1. Mean pairwise between-species distances (DUSE-DUCY, DUSE-DUAB, DUCY-DUAB)
#      with permutation-based significance tests (accounts for non-independence)
#   2. Focal putative hybrid CY_HUN_LP_267_Du-686:
#      mean distance to each species + permutation test for species affinity
#
# Evan Hackstadt
# Whittall Lab Dudleya Genomics

# Note: generated by Claude Sonnet 4.6


import os
import numpy as np
import pandas as pd
from itertools import combinations

# ── Constants ──────────────────────────────────────────────────────────────────

HYBRID_LABEL = "CY_BOU_LP_290_Du-739"
N_PERMUTATIONS = 10_000
RNG_SEED = 42

SPECIES_COLORS = {"DUSE": "D. setchellii", "DUCY": "D. cymosa", "DUAB": "D. abramsii"}
BETWEEN_PAIRS = [("DUSE", "DUCY"), ("DUSE", "DUAB"), ("DUCY", "DUAB")]


# ── Helper functions ───────────────────────────────────────────────────────────

def infer_species(sample_name: str) -> str:
    """
    Infer species from population code, matching logic in pcangsd_visualize.py.
    Samples with an underscore in the popcode prefix are non-setchellii.
    """
    # popcode is everything before the first '_LP_'
    substrings = sample_name.split("_LP_")
    popcode = substrings[0]

    if "_" in popcode:
        prefix = popcode.split("_")[0]
        if prefix == "CY":
            return "DUCY"
        elif prefix in ("ABAB", "ABBE", "ABMU"):
            return "DUAB"
    return "DUSE"


def parse_distance_matrix(path: str):
    """
    Parse ngsDist distance matrix.

    Returns
    -------
    labels : list of str
    dist   : np.ndarray, shape (N, N), symmetric
    """
    with open(path) as fh:
        lines = fh.readlines()

    # Line 0: empty; Line 1: N; Lines 2+: data
    n = int(lines[1].strip())
    labels = []
    rows = []

    for line in lines[2:]:
        line = line.strip()
        if not line:
            continue
        parts = line.split("\t")
        labels.append(parts[0])
        rows.append([float(x) for x in parts[1:]])

    dist = np.array(rows)
    assert dist.shape == (n, n), f"Expected ({n},{n}) matrix, got {dist.shape}"
    return labels, dist


def between_group_distances(dist: np.ndarray, idx_a: np.ndarray, idx_b: np.ndarray) -> np.ndarray:
    """
    Extract all pairwise distances between two non-overlapping index sets.
    Returns a flat array of distances.
    """
    return dist[np.ix_(idx_a, idx_b)].ravel()


def permutation_test_between_groups(
    dist: np.ndarray,
    idx_a: np.ndarray,
    idx_b: np.ndarray,
    idx_c: np.ndarray,
    n_perm: int = N_PERMUTATIONS,
    rng: np.random.Generator = None,
) -> tuple[float, float]:
    """
    Permutation test: is mean(dist[A,B]) != mean(dist[A,C])?

    The test statistic is: mean(A-B) - mean(A-C).
    We permute labels within B ∪ C and recompute the statistic.

    Returns
    -------
    observed : float  — observed statistic
    p_value  : float  — two-tailed permutation p-value
    """
    if rng is None:
        rng = np.random.default_rng(RNG_SEED)

    obs = between_group_distances(dist, idx_a, idx_b).mean() - \
          between_group_distances(dist, idx_a, idx_c).mean()

    # Pool B and C, permute membership
    pool = np.concatenate([idx_b, idx_c])
    nb = len(idx_b)
    null = np.empty(n_perm)

    for i in range(n_perm):
        shuffled = rng.permutation(pool)
        perm_b, perm_c = shuffled[:nb], shuffled[nb:]
        null[i] = (between_group_distances(dist, idx_a, perm_b).mean() -
                   between_group_distances(dist, idx_a, perm_c).mean())

    p = np.mean(np.abs(null) >= np.abs(obs))
    return float(obs), float(p)


def focal_permutation_test(
    dist: np.ndarray,
    focal_idx: int,
    idx_a: np.ndarray,
    idx_b: np.ndarray,
    n_perm: int = N_PERMUTATIONS,
    rng: np.random.Generator = None,
) -> tuple[float, float, float]:
    """
    For a single focal sample, test whether its mean distance to group A
    differs from its mean distance to group B.

    Permutes labels within A ∪ B.

    Returns
    -------
    mean_a   : float
    mean_b   : float
    p_value  : float  (two-tailed)
    """
    if rng is None:
        rng = np.random.default_rng(RNG_SEED)

    focal_row = dist[focal_idx]
    mean_a = focal_row[idx_a].mean()
    mean_b = focal_row[idx_b].mean()
    obs = mean_a - mean_b

    pool = np.concatenate([idx_a, idx_b])
    na = len(idx_a)
    null = np.empty(n_perm)

    for i in range(n_perm):
        shuffled = rng.permutation(pool)
        perm_a, perm_b = shuffled[:na], shuffled[na:]
        null[i] = focal_row[perm_a].mean() - focal_row[perm_b].mean()

    p = np.mean(np.abs(null) >= np.abs(obs))
    return float(mean_a), float(mean_b), float(p)


def stderr(arr: np.ndarray) -> float:
    return float(np.std(arr, ddof=1) / np.sqrt(len(arr)))


def format_p(p: float) -> str:
    if p < 0.001:
        return "p < 0.001"
    return f"p = {p:.3f}"


# ── Main ───────────────────────────────────────────────────────────────────────

def analyze_distances(dist_path: str, out_path: str):
    rng = np.random.default_rng(RNG_SEED)

    # ── Parse ──────────────────────────────────────────────────────────────────
    labels, dist = parse_distance_matrix(dist_path)
    n = len(labels)

    species = [infer_species(lbl) for lbl in labels]
    df_meta = pd.DataFrame({"label": labels, "species": species})

    idx = {sp: np.where(np.array(species) == sp)[0] for sp in ("DUSE", "DUCY", "DUAB")}
    counts = {sp: len(v) for sp, v in idx.items()}

    # ── Identify hybrid ────────────────────────────────────────────────────────
    if HYBRID_LABEL in labels:
        hybrid_idx = labels.index(HYBRID_LABEL)
        hybrid_found = True
    else:
        hybrid_idx = None
        hybrid_found = False

    # ── Between-species distances ──────────────────────────────────────────────
    between = {}
    for sp_a, sp_b in BETWEEN_PAIRS:
        d = between_group_distances(dist, idx[sp_a], idx[sp_b])
        between[(sp_a, sp_b)] = d

    # Permutation tests: three pairwise comparisons share a common species.
    # We test each pair difference using the species not shared as the anchor.
    #
    # DUSE-DUCY vs DUSE-DUAB  →  anchor = DUSE,  compare DUCY vs DUAB labels
    # DUSE-DUCY vs DUCY-DUAB  →  anchor = DUCY,  compare DUSE vs DUAB labels
    # DUSE-DUAB vs DUCY-DUAB  →  anchor = DUAB,  compare DUSE vs DUCY labels

    perm_tests = [
        ("DUSE-DUCY vs DUSE-DUAB", "DUSE", "DUCY", "DUAB"),
        ("DUSE-DUCY vs DUCY-DUAB", "DUCY", "DUSE", "DUAB"),
        ("DUSE-DUAB vs DUCY-DUAB", "DUAB", "DUSE", "DUCY"),
    ]

    perm_results = {}
    for label, anchor, g1, g2 in perm_tests:
        obs, p = permutation_test_between_groups(
            dist, idx[anchor], idx[g1], idx[g2], rng=rng
        )
        perm_results[label] = (obs, p)

    # ── Hybrid analysis ────────────────────────────────────────────────────────
    hybrid_results = {}
    if hybrid_found:
        # Exclude hybrid from species index sets to avoid self-comparison artifacts
        # (hybrid was assigned DUCY by infer_species but we treat it separately)
        idx_duse_clean = idx["DUSE"]
        idx_ducy_clean = idx["DUCY"][idx["DUCY"] != hybrid_idx]
        idx_duab_clean = idx["DUAB"]

        # Mean distances to each species
        hybrid_row = dist[hybrid_idx]
        mean_duse = hybrid_row[idx_duse_clean].mean()
        mean_ducy = hybrid_row[idx_ducy_clean].mean()
        mean_duab = hybrid_row[idx_duab_clean].mean()

        # Pairwise permutation tests between the hybrid's affinities
        # Test 1: Is dist(hybrid, DUSE) != dist(hybrid, DUCY)?
        m_duse, m_ducy, p_duse_ducy = focal_permutation_test(
            dist, hybrid_idx, idx_duse_clean, idx_ducy_clean, rng=rng
        )
        # Test 2: Is dist(hybrid, DUSE) != dist(hybrid, DUAB)?
        _, m_duab, p_duse_duab = focal_permutation_test(
            dist, hybrid_idx, idx_duse_clean, idx_duab_clean, rng=rng
        )
        # Test 3: Is dist(hybrid, DUCY) != dist(hybrid, DUAB)?
        m_ducy2, _, p_ducy_duab = focal_permutation_test(
            dist, hybrid_idx, idx_ducy_clean, idx_duab_clean, rng=rng
        )

        hybrid_results = {
            "mean_duse": mean_duse, "se_duse": stderr(hybrid_row[idx_duse_clean]),
            "mean_ducy": mean_ducy, "se_ducy": stderr(hybrid_row[idx_ducy_clean]),
            "mean_duab": mean_duab, "se_duab": stderr(hybrid_row[idx_duab_clean]),
            "p_duse_vs_ducy": p_duse_ducy,
            "p_duse_vs_duab": p_duse_duab,
            "p_ducy_vs_duab": p_ducy_duab,
        }

    # ── Write report ───────────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    lines_out = []
    w = lines_out.append  # shorthand

    w("=" * 70)
    w("ngsDist Genetic Distance Analysis")
    w("=" * 70)
    w(f"\nDataset: {dist_path}")
    w(f"Samples: {n}  |  DUSE: {counts['DUSE']}  DUCY: {counts['DUCY']}  DUAB: {counts['DUAB']}")
    w(f"Permutations: {N_PERMUTATIONS:,}  |  RNG seed: {RNG_SEED}\n")

    w("─" * 70)
    w("BETWEEN-SPECIES PAIRWISE DISTANCES")
    w("─" * 70)
    w(f"  {'Comparison':<22}  {'N pairs':>8}  {'Mean':>10}  {'SE':>10}")
    w(f"  {'─'*22}  {'─'*8}  {'─'*10}  {'─'*10}")

    for sp_a, sp_b in BETWEEN_PAIRS:
        d = between[(sp_a, sp_b)]
        label_str = f"{SPECIES_COLORS[sp_a]} vs {SPECIES_COLORS[sp_b]}"
        w(f"  {label_str:<40}  N={len(d):>6}  mean={d.mean():.6f}  SE={stderr(d):.6f}")

    w("")
    w("  Note: SE reflects dispersion across all pairwise comparisons.")
    w("  Standard errors are inflated/misleading due to non-independence")
    w("  (each sample contributes to multiple pairs). See permutation")
    w("  tests below for valid inference.\n")

    w("─" * 70)
    w("PERMUTATION TESTS (two-tailed, N=" + str(N_PERMUTATIONS) + ")")
    w("─" * 70)
    w("")
    w("  For each test, species labels in the two non-anchor groups are")
    w("  permuted to generate a null distribution of mean-difference")
    w("  statistics. This preserves the correlation structure of the")
    w("  distance matrix.\n")
    w(f"  {'Comparison':<40}  {'Obs. Δ mean':>12}  {'p-value':>12}")
    w(f"  {'─'*40}  {'─'*12}  {'─'*12}")

    for label, (obs, p) in perm_results.items():
        # Translate internal label to readable form
        readable = (label
                    .replace("DUSE", "D.setch.")
                    .replace("DUCY", "D.cymosa")
                    .replace("DUAB", "D.abrams."))
        w(f"  {readable:<40}  {obs:>+12.6f}  {format_p(p):>12}")

    w("")

    w("─" * 70)
    w(f"PUTATIVE HYBRID: {HYBRID_LABEL}")
    w("─" * 70)
    w("")

    if not hybrid_found:
        w(f"  WARNING: '{HYBRID_LABEL}' not found in distance matrix.")
        w("  Check that the sample label matches exactly.\n")
    else:
        hr = hybrid_results
        w(f"  Mean genetic distance to each species group:\n")
        w(f"    {'Group':<30}  {'N':>5}  {'Mean dist':>12}  {'SE':>10}")
        w(f"    {'─'*30}  {'─'*5}  {'─'*12}  {'─'*10}")

        groups = [
            ("D. setchellii (DUSE)", counts["DUSE"],    hr["mean_duse"], hr["se_duse"]),
            ("D. cymosa (DUCY)*",    len(idx_ducy_clean), hr["mean_ducy"], hr["se_ducy"]),
            ("D. abramsii (DUAB)",   counts["DUAB"],    hr["mean_duab"], hr["se_duab"]),
        ]
        for gname, gn, gm, gs in groups:
            w(f"    {gname:<30}  {gn:>5}  {gm:>12.6f}  {gs:>10.6f}")

        w(f"\n  * Hybrid excluded from the D. cymosa group for self-comparison.")
        w(f"\n  Permutation tests (focal vs. two groups, labels permuted within pool):\n")
        w(f"    {'Comparison':<36}  {'Obs. Δ mean':>12}  {'p-value':>12}")
        w(f"    {'─'*36}  {'─'*12}  {'─'*12}")

        focal_tests = [
            ("D.setch. vs D.cymosa",
             hr["mean_duse"] - hr["mean_ducy"], hr["p_duse_vs_ducy"]),
            ("D.setch. vs D.abramsii",
             hr["mean_duse"] - hr["mean_duab"], hr["p_duse_vs_duab"]),
            ("D.cymosa vs D.abramsii",
             hr["mean_ducy"] - hr["mean_duab"], hr["p_ducy_vs_duab"]),
        ]
        for gname, obs, p in focal_tests:
            w(f"    {gname:<36}  {obs:>+12.6f}  {format_p(p):>12}")

        w("")
        w("  Interpretation guide:")
        w("  A hybrid between DUSE and DUCY would show intermediate distances,")
        w("  i.e., dist(DUSE) ≈ dist(DUCY) < dist(DUAB), or a non-significant")
        w("  DUSE-vs-DUCY test paired with a significant DUSE-vs-DUAB test.")
        w("  A pure DUCY individual would show dist(DUCY) << dist(DUSE).")
        w("")

    w("─" * 70)
    w("SAMPLE METADATA")
    w("─" * 70)
    w(f"\n  {'Sample':<45}  {'Species':>8}")
    w(f"  {'─'*45}  {'─'*8}")
    for lbl, sp in zip(labels, species):
        marker = "  <── FOCAL HYBRID" if lbl == HYBRID_LABEL else ""
        w(f"  {lbl:<45}  {sp:>8}{marker}")

    w("")
    w("=" * 70)
    w("END OF REPORT")
    w("=" * 70)

    report_str = "\n".join(lines_out)
    with open(out_path, "w") as fh:
        fh.write(report_str)

    print(report_str)
    print(f"\nReport written to: {out_path}")


# ── Snakemake entrypoint ───────────────────────────────────────────────────────

dist_path = snakemake.input.dist
out_path  = snakemake.output.report

analyze_distances(dist_path, out_path)